### ISSUE TITLE
[Feature Request] The ability to toggle off the conversion of Minecraft color codes to MiniMessage codes within placeholders

### ISSUE THREAD

**Issue by Weasel-Beans** [jpenilla/AnnouncerPlus#112]
**Is your feature request related to a problem? Please describe.**
As it stands, I cannot use placeholders in commands that broadcast messages to users if that placeholder contains it's own formatting codes (&6, etc), because this plugin parses those placeholders and replaces it auto*magically* with the \<code>\</code> format.

**Describe the solution you'd like**
The ability to toggle this feature off in general, and/or some way to disable it as-needed with certain placeholders. Perhaps by placing it within another like %NoReformat_{Placeholder}%

**Describe alternatives you've considered**
Avoiding the use of placeholders entirely, which is not possible for all uses.

**Additional context**
What I was trying to do is send a command using a broadcast plugin with the vault prefix/suffix as a placeholder to save time. Instead it returns a mess of formatting that doesn't work at all in Minecraft. In this case I can spend more time to make individual files for each group, but this issue would persist for other uses.

**Comment by jpenilla** [comment]
An option to "not convert" is probably a no-go for a variety of reasons (it doesn't align with the vision for the plugin, and also technical reasons).

The conversion from legacy should be lossless however. Do you have an example of a failed conversion that "doesn't work at all in Minecraft"? The conversion seems to work fine in my testing.

**Comment by Weasel-Beans** [comment]
Join commands as they appear in the given join/quit file:
![joincommands](https://user-images.githubusercontent.com/49420418/177439208-5a4f800d-f7ed-4b11-a4e6-ecd17a33b4f8.PNG)

What appears in-game:
![joinmessageformat](https://user-images.githubusercontent.com/49420418/177439226-af790460-c346-4815-bf18-f7c2e44a429d.PNG)

The user's suffix in LuckPerms:
![joinsuffix](https://user-images.githubusercontent.com/49420418/177439243-576e4f9e-ce27-49de-9d8d-62edb97ed556.PNG)

What should appear when this placeholder is parsed in-game:
![joinpapiparse](https://user-images.githubusercontent.com/49420418/177439246-263f09bb-f1f1-44ad-af01-3dcaa43d90ad.PNG)

Now that I think about it, this may be more of a bug than anything as I'm not sure when you'd want it to convert a placeholder's contents like that. Perhaps it's simply converting the Minecraft codes into the new format but not processing them when it's done from a placeholder.

**Comment by jpenilla** [comment]
I think the best solution is for you to use the built-in `join-messages`/`join-broadcasts` config options instead of using a second plugin to broadcast messages through a command. Either that or use the `/ap broadcast` command. Both of these solutions require changing the text in the AP config files from legacy to MiniMessage, any legacy placeholders will be upgraded automatically.

Although there is an unintended side-effect happening there from parsing placeholders in commands, it's not something you would encounter with a more sane/standard/supported setup of using the in-built config options or commands instead of executing another plugin's command, and so it's probably not going to be fixed. Placeholder parsing in commands is needed for `%player_name%` placeholders for example, and we can't know which placeholders are needed for the command and which are meant to be parsed by the command we are executing. Given we can't remove placeholder parsing for commands as is, we also can't remove format conversion as this would break executing `/ap broadcast` with placeholders from config commands, which is higher priority to work than third party plugin commands.

**Comment by jpenilla** [comment]
As much as I would like to fix this, it's very much an edge case and fixing it simply would break other things which are more commonly done. There are of course much more complicated solutions to the one I'm thinking of that could be attempted, but that's more than I'm willing to do for an edge case involving legacy codes like this atm.
