### ISSUE TITLE
[Bug Report] no automessages are sent when random-message-order=false

### ISSUE THREAD

**Issue by Agrrox** [jpenilla/AnnouncerPlus#57]
**Describe the bug**
When I set random-message-order=false, no messages are sent to chat from the automessage config.
When I set random-message-order=true, messages are sent to chat from the automessage config.

*** 

**To Reproduce**
1. download the provided configuration
2. change the settings
3. use /ap reload

*** 

**Screenshots**

<details><summary>random-message-order=false</summary>

![2021-04-03_14 39 26](https://user-images.githubusercontent.com/10901821/113478704-d3846900-948a-11eb-9f47-6b997741b642.png)
</details>

<details><summary>random-message-order=true</summary>

![2021-04-03_14 40 29](https://user-images.githubusercontent.com/10901821/113478707-d5e6c300-948a-11eb-992d-81c1808e675a.png)
</details>

*** 

**Server Software and Version:**
 - Vendor: Mohist
 - Minecraft Version: 1.12.2
 - Output of /version command: Mohist version 1.12.2-198 (MC 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge 14.23.5.2854)

**Additional context**
AnnouncerPlus 1.2.4
server is part of Bungeecord network.

chat formatting plugins on server:
VentureChat
AdvancedBan

**Config files**
[AnnouncerPlus.zip](https://github.com/jpenilla/AnnouncerPlus/files/6252561/AnnouncerPlus.zip)

**Comment by jpenilla** [comment]
It seems like the issue is that in `everyone.conf`, the first message has all of it's elements disabled. Meaning that with `random-message-order=false`, a random message would be chosen on each reload, and with `random-message-order=true`, the first (empty) message was always displayed first.

By temporarily changing the delay from 5 minutes to 5 seconds, this can be better illustrated,

**Comment by Agrrox** [comment]
Problem solved, this was a mistake on my side.
